name: SampleRouter
options:
  bundleIdPrefix: com.sakiyamaK
  deploymentTarget:
    iOS: 12.0
configs:
  Debug: debug
  Release: release
schemes:
  SampleRouter:
    build:
      targets:
        SampleRouter: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - SampleRouter
      targets:
        - name: SampleRouterTests
          # parallelizable: true
          randomExecutionOrder: true
        - name: SampleRouterUITests
        #   # parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  SampleRouter:
    platform: iOS
    type: application
    sources:
      - path: SampleRouter/
        optional: true
    scheme:
        testTargets:
            - SampleRouterTests
            - SampleRouterUITests

  # Unit Test
  SampleRouterTests:
    platform: iOS
    type: bundle.unit-test
    sources: SampleRouterTests
    dependencies:
      - target: SampleRouter

  # UI Test
  SampleRouterUITests:
    platform: iOS
    type: bundle.unit-test
    sources: SampleRouterUITests
    dependencies:
      - target: SampleRouter
    settings:
      TEST_TARGET_NAME: SampleRouter
      INFOPLIST_FILE: SampleRouterUITests/Info.plist